dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.1
  - Uniswap/v2-core@1.0.1
compiler:
  solc:
    version: 0.5.16
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.1"
      - "@Uniswap=Uniswap/v2-core@1.0.1"
dotenv: .env
networks:
  defaults: ganache-local
  rinkeby2:
    verify: true
  mainnet-fork-dev:
    verify: false
  development:
    verify: false
  ganache-local:
    verify: false
wallets:
  from_key: ${PRIVATE_KEY}
